title: www.aka.ms/addcomputer - Get the Code to Link Phone to PC
description: <a href="https://computersolve.com/www-aka-ms-yourpc/"><img src="/button1.png"alt="www.aka.ms/addcomputer"/></a>
theme: jekyll-theme-cayman
google_analytics: UA-277913547-1
